// <auto-generated />
using System;
using ArticleService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArticleService.Migrations
{
    [DbContext(typeof(ArticleDbContext))]
    partial class ArticleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArticleService.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateMiseAJour")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DureeGarantie")
                        .HasColumnType("int");

                    b.Property<bool>("EstDisponible")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Modele")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Prix")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Categorie");

                    b.HasIndex("Marque");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.ToTable("Articles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categorie = "Sanitaire",
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mitigeur chromé pour lavabo avec économiseur d'eau",
                            DureeGarantie = 60,
                            EstDisponible = true,
                            Marque = "Grohe",
                            Modele = "Eurosmart",
                            Nom = "Robinet Mitigeur Lavabo",
                            Prix = 89.99m,
                            Reference = "ROB-LAV-001",
                            Stock = 25,
                            Type = "Robinetterie"
                        },
                        new
                        {
                            Id = 2,
                            Categorie = "Sanitaire",
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mitigeur thermostatique pour douche",
                            DureeGarantie = 60,
                            EstDisponible = true,
                            Marque = "Hansgrohe",
                            Modele = "ShowerSelect",
                            Nom = "Robinet Mitigeur Douche",
                            Prix = 245.00m,
                            Reference = "ROB-DOU-001",
                            Stock = 15,
                            Type = "Robinetterie"
                        },
                        new
                        {
                            Id = 3,
                            Categorie = "Sanitaire",
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "WC suspendu avec chasse d'eau économique",
                            DureeGarantie = 24,
                            EstDisponible = true,
                            Marque = "Geberit",
                            Modele = "Rimfree",
                            Nom = "WC Suspendu Compact",
                            Prix = 320.00m,
                            Reference = "WC-SUS-001",
                            Stock = 10,
                            Type = "WC"
                        },
                        new
                        {
                            Id = 4,
                            Categorie = "Sanitaire",
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lavabo rectangulaire 60x45cm",
                            DureeGarantie = 24,
                            EstDisponible = true,
                            Marque = "Ideal Standard",
                            Modele = "Connect",
                            Nom = "Lavabo en Céramique",
                            Prix = 125.00m,
                            Reference = "LAV-CER-001",
                            Stock = 20,
                            Type = "Lavabo"
                        },
                        new
                        {
                            Id = 5,
                            Categorie = "Sanitaire",
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Baignoire rectangulaire 170x75cm",
                            DureeGarantie = 120,
                            EstDisponible = true,
                            Marque = "Villeroy & Boch",
                            Modele = "Oberon",
                            Nom = "Baignoire Acrylique",
                            Prix = 580.00m,
                            Reference = "BAI-ACR-001",
                            Stock = 8,
                            Type = "Baignoire"
                        },
                        new
                        {
                            Id = 6,
                            Categorie = "Chauffage",
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chaudière à condensation 24kW",
                            DureeGarantie = 24,
                            EstDisponible = true,
                            Marque = "Viessmann",
                            Modele = "Vitodens 100-W",
                            Nom = "Chaudière Gaz Murale",
                            Prix = 2850.00m,
                            Reference = "CHAU-GAZ-001",
                            Stock = 5,
                            Type = "Chaudière"
                        },
                        new
                        {
                            Id = 7,
                            Categorie = "Chauffage",
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chaudière au sol à condensation 30kW",
                            DureeGarantie = 24,
                            EstDisponible = true,
                            Marque = "De Dietrich",
                            Modele = "MCR-G 24/28 MI+",
                            Nom = "Chaudière Gaz Sol",
                            Prix = 3450.00m,
                            Reference = "CHAU-GAZ-002",
                            Stock = 3,
                            Type = "Chaudière"
                        },
                        new
                        {
                            Id = 8,
                            Categorie = "Chauffage",
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Radiateur acier type 22 - 600x1000mm",
                            DureeGarantie = 120,
                            EstDisponible = true,
                            Marque = "Thermor",
                            Modele = "Evidence",
                            Nom = "Radiateur Acier Panneau",
                            Prix = 185.00m,
                            Reference = "RAD-ACR-001",
                            Stock = 30,
                            Type = "Radiateur"
                        },
                        new
                        {
                            Id = 9,
                            Categorie = "Chauffage",
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Radiateur design vertical 1800mm",
                            DureeGarantie = 120,
                            EstDisponible = true,
                            Marque = "Acova",
                            Modele = "Fassane",
                            Nom = "Radiateur Aluminium Design",
                            Prix = 425.00m,
                            Reference = "RAD-ALU-001",
                            Stock = 12,
                            Type = "Radiateur"
                        },
                        new
                        {
                            Id = 10,
                            Categorie = "Chauffage",
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thermostat intelligent WiFi programmable",
                            DureeGarantie = 24,
                            EstDisponible = true,
                            Marque = "Nest",
                            Modele = "Learning Thermostat",
                            Nom = "Thermostat Connecté",
                            Prix = 249.00m,
                            Reference = "THER-CON-001",
                            Stock = 18,
                            Type = "Thermostat"
                        },
                        new
                        {
                            Id = 11,
                            Categorie = "Chauffage",
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vanne thermostatique pour radiateur",
                            DureeGarantie = 60,
                            EstDisponible = true,
                            Marque = "Danfoss",
                            Modele = "RA-N",
                            Nom = "Vanne Thermostatique",
                            Prix = 45.00m,
                            Reference = "VAN-THER-001",
                            Stock = 50,
                            Type = "Accessoire"
                        },
                        new
                        {
                            Id = 12,
                            Categorie = "Chauffage",
                            DateCreation = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pompe à chaleur air-eau 8kW",
                            DureeGarantie = 36,
                            EstDisponible = true,
                            Marque = "Daikin",
                            Modele = "Altherma 3",
                            Nom = "Pompe à Chaleur Air-Eau",
                            Prix = 5200.00m,
                            Reference = "PAC-AIR-001",
                            Stock = 2,
                            Type = "Pompe à Chaleur"
                        });
                });

            modelBuilder.Entity("ArticleService.Models.CustomerArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAchat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFinGarantie")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateMiseAJour")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstSousGarantie")
                        .HasColumnType("bit");

                    b.Property<string>("NumeroFacture")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Remarques")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ClientId");

                    b.HasIndex("DateAchat");

                    b.HasIndex("NumeroSerie")
                        .IsUnique();

                    b.ToTable("CustomerArticles", (string)null);
                });

            modelBuilder.Entity("ArticleService.Models.CustomerArticle", b =>
                {
                    b.HasOne("ArticleService.Models.Article", "Article")
                        .WithMany("ArticlesClients")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("ArticleService.Models.Article", b =>
                {
                    b.Navigation("ArticlesClients");
                });
#pragma warning restore 612, 618
        }
    }
}
